# Generated by Django 3.2.14 on 2022-07-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pic', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='places_images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.places')),
            ],
        ),
    ]
