# Generated by Django 3.2.14 on 2022-07-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
