# Generated by Django 4.0.6 on 2022-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_places_place_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('id_pic',)},
        ),
        migrations.AlterField(
            model_name='images',
            name='id_pic',
            field=models.PositiveSmallIntegerField(blank=b'I00\n', default=0, null=b'I00\n'),
        ),
    ]
