# Generated by Django 4.0.6 on 2022-07-19 09:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_images_options_alter_images_id_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=tinymce.models.HTMLField(),
        ),
    ]
