# Generated by Django 4.0.6 on 2022-07-21 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_images_options_alter_places_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
