# Generated by Django 4.0.6 on 2022-07-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_places_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='place_id',
        ),
    ]
