# Generated by Django 4.0.6 on 2022-07-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_places_latitude_alter_places_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.places'),
        ),
    ]
