# Generated by Django 4.0.6 on 2022-07-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_images_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('order_num',), 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.RenameField(
            model_name='images',
            old_name='id_pic',
            new_name='order_num',
        ),
    ]
